### ISSUE TITLE
The shield break sound fix still plays even when it shouldn't.

### ISSUE THREAD

**Issue by realFusionFusion** [uku3lig/bettershields#1]
Let me explain. It isn't actually possible to break someone's shield if they are in their damage tick. You would have to wait for their damage tick to end before breaking their shield. But despite that the mod still plays a break shield sound if I hit a shielded player with an axe even if they are in their damage tick.

Damage tick = The red phase that the player goes through when they are hit.

**Comment by uku3lig** [comment]
i tried this in 1.19.4 and the shield breaks while the player is in the damage tick

edit: shield breaks on 1.18.2 too

**Comment by realFusionFusion** [comment]
Try doing the damage tick with something that does more damage than an axe spam hit like a fully charged sword hit or a crystal hit. Doing like this will not let you stack multiple hits like what happened when you tried testing it.

**Comment by uku3lig** [comment]
no matter what i try, the shield breaks every single time

edit: here's a video

https://github.com/uku3lig/bettershields/assets/61147779/8ef4a271-75a2-4cf3-98d2-7c424135244d

**Comment by realFusionFusion** [comment]
What??????????
That is very, very weird... I demonstrated this bug in a video and in it everything behaves exactly how I described to you (you can't disable shield while they are in their damage tick + it plays a break shield sound if you hit them with an axe anyways BUT only if you hit them with a sword first, not a crystal). Here's the video:

https://youtu.be/O7C4qZTMMGg (notice how I didn't even disable their shield, all my axe hits were within their damage tick)

What version did you play on in the video you showed? Maybe not being able disable a shield in the circumstance I showed you is actually a bug within the game itself?

Edit: I tested on LAN, on MCPvP and EUPvP, all while being on 1.20.1.

**Comment by uku3lig** [comment]
as far as i know, the axe needs to be fully loaded for the shield to be broken, so a sound is indeed played incorrectly, but for a different reason

also, i did my testing on 1.19.4 and 1.18.2, i'll test again in 1.20.1 just to make sure

**Comment by realFusionFusion** [comment]
Are there any updates?

**Comment by realFusionFusion** [comment]
Hi Uku, it has been 2 weeks since the bug report was posted, I am just wondering how things are going? I hope this message is not bothersome to you

**Comment by uku3lig** [comment]
even while being on a damage tick, hitting with a non fully charged axe breaks the shield

(sorry for the wait, i was busy and demotivated)

**Comment by realFusionFusion** [comment]
Right, if that is true then why is the video I sent saying otherwise? I am guessing that the video was simply forgotten, so here it is again: 
https://youtu.be/O7C4qZTMMGg (again look at all my axe hits, they all happen during their damage tick so notice how the second hit doesn't even disable the shield).

Maybe it happens because I hit them first with a sword and this is on a normal server and not a LAN server? If you want to see the bug for yourself then just try playing against someone who uses a shield on a normal server, it makes things so much simpler. It will take some time for the bug to happen in that case so keep that in mind.

**Comment by uku3lig** [comment]
i didn't forget your video, but i have no clue why the shield didn't break there

i'll try to do some testing when i can

**Comment by realFusionFusion** [comment]
Hey Uku, did you find anything yet? I hope this is not bothering you too much

**Comment by uku3lig** [comment]
im on vacation until the 15th :)

**Comment by realFusionFusion** [comment]
Oh, I see, enjoy your holiday! :D
