### ISSUE TITLE
The latest beta version of 1.20.1 Ukulib crashes the game upon startup

### ISSUE THREAD

**Issue by realFusionFusion** [uku3lig/bettershields#2]
This happens whenever you have that mod and BetterShields combined but doesn't if you have the latest release version of the Ukulib mod.

**Comment by uku3lig** [comment]
bettershields does not work yet with ukulib 1.0; the only compatible mods at the moment are betterhurtcam and uku's armor hud

porting all my mods to it is planned, but it will take a little bit of time
