### ISSUE TITLE
Coloring broken

### ISSUE THREAD

**Issue by Jes-debug** [uku3lig/bettershields#6]
It doesnt color when disabled or raising..

it used to color orange when raising but it just stopped now

also it never turned redwhen disabled

**Comment by uku3lig** [comment]
hello, thank you for the report!

could you please indicate which minecraft and mod versions you are using?

**Comment by tooanri4you** [comment]
I'm not OP but it also isn't really working for me. When it comes to other players it doesn't work, it only works when it's my shield the one getting disabled. I'm using 1.21.1, bettershields 1.3.0+mc1.21, ukulib 1.3.0+mc1.21.

**Comment by uku3lig** [comment]
shield coloring for other players has not been implemented yet, that's why it doesn't work

as for op, i tested again and everything works fine
